# Namespace where the application will be deployed
namespace: "dev"

# Prefix for the repository where Helm charts are hosted
repository_prefix: "ardhmd"

visits:
  # Hostname or IP address of the database server for the 'visits' service
  dbhost: "cgtn3gql0yfa.eu-west-3.rds.amazonaws.com:3306"
  # Name of the database for the 'visits' service
  dbname: "visitsdb"
  # Username for connecting to the 'visits' database
  dbuser: "admin"